name: Tarefa
description: Atividade ou processo a ser feito
title: "Tarefa: "
labels: ["tarefa"]
assignees: []
body:
  - type: dropdown
    id: prioridade
    attributes:
      label: Prioridade
      description: Selecione o nível de urgência
      options:
        - "🔴 Alta (Bloqueia trabalho/urgente)"
        - "🟡 Média (Importante mas não bloqueante)"
        - "🟢 Baixa (Backlog/não crítica)"
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: Descrição da tarefa
      description: Detalhe o que precisa ser feito
    validations:
      required: true

  - type: textarea
    id: criterios
    attributes:
      label: Critérios de aceitação
      description: Liste as condições para considerar a tarefa concluída
      placeholder: |
        - [ ] Critério 1
        - [ ] Critério 2
    validations:
      required: true

  - type: textarea
    id: contexto
    attributes:
      label: Contexto adicional
      description: Adicione explicações extras, prints, trechos de código etc
    validations:
      required: false

  - type: textarea
    id: dependencias
    attributes:
      label: Dependências
      description: "Relacione com outros issues (ex: Relacionado a #123 ou Bloqueia #456)"
      placeholder: |
        - Relacionado a #123
        - Bloqueia #456
    validations:
      required: false